//
//  LambdaTests.h
//  LambdaTest
//
//  Created by Phil McCarthy on 06/10/2013.
//  Copyright (c) 2013 Phil McCarthy. All rights reserved.
//

#ifndef LambdaTest_LambdaTests_h
#define LambdaTest_LambdaTests_h

#include <string>

static const std::string REFERENCE_STRING = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Aliquam eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, at venenatis sem sodales. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, libero et consectetur hendrerit, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit.";


static const std::string INSERTION_AT_BEGINNING = "Here is some text inserted at the very beginning. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Aliquam eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, at venenatis sem sodales. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, libero et consectetur hendrerit, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit.";


static const std::string INSERTION_AT_END = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Aliquam eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, at venenatis sem sodales. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, libero et consectetur hendrerit, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit. Here is some text that is inserted pretty much at the end of this string.";


static const std::string SECTION_MOVE_TO_BEGINNING = "interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, at venenatis sem sodales. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, libero et consectetur hendrerit, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Aliquam eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel";


static const std::string BEGINNING_DELETED = "Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, at venenatis sem sodales. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, libero et consectetur hendrerit, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit.";


static const std::string END_DELETED = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Aliquam eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo interdum. Vivamus ligula lorem, molestie";


static const std::string DELETIONS_AND_INSERTIONS = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada risus eget risus condimentum suscipit. Duis vitae tempus mi. Sed blandit leo eu eros tempus euismod. Cras id posuere justo. Maecenas vel fringilla orci. Maecenas a eros eget massa scelerisque blandit eget at lacus. Proin fringilla purus ac mattis pharetra. Ut facilisis elementum mi. Praesent placerat ullamcorper fringilla. Maecenas consectetur adipiscing nibh nec varius. In sed leo felis. Sed est dolor, venenatis eu erat at, interdum luctus felis. Morbi sed molestie lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\
\
Aliquam erat volutpat. Etiam pharetra nulla in tristique luctus. Random word eu orci eu lacus viverra gravida. Suspendisse id condimentum libero. Sed quis sagittis lorem, dapibus molestie nunc. Sed pellentesque lectus molestie nisi elementum dictum. In hac habitasse platea dictumst. Cras nec tortor euismod, fringilla nunc non, ultrices lorem. Vivamus ornare auctor velit non sodales. Nunc quam nulla, faucibus id consectetur id, dictum in turpis. Aliquam ut mauris nec risus mollis faucibus in vel tortor. In nec elit congue, laoreet tortor a, consequat neque. Mauris eu consequat metus. In elit massa, vulputate porta risus id, facilisis pulvinar lectus. Proin et magna pharetra, fringilla metus vitae, congue nibh.\
\
Donec sed risus enim. Aliquam et erat eu nisl eleifend varius. Pellentesque porttitor tellus eu risus commodo dragon interdum. Vivamus ligula lorem, molestie et risus eget, egestas fermentum dolor. Donec sit amet augue tellus. In facilisis blandit eros, vel interdum est consectetur in. Cras non consectetur dui, ac commodo orci. Vivamus quis rutrum nibh. Nunc bibendum ut dui et dictum. Nulla non ullamcorper justo. Nulla facilisi. Nam non volutpat arcu, quis semper purus. In lacinia leo eu molestie fermentum.\
\
Praesent pharetra mauris sit amet metus suscipit, wow latin sure is boring. Sed vulputate enim molestie scelerisque blandit. Phasellus vitae odio eu felis bibendum aliquet. Nunc et gravida libero. Sed mi velit, luctus in fringilla quis, blandit eu ipsum. Proin non feugiat nibh. Nulla in neque eget elit adipiscing varius. Sed is an awesom linux command egestas tortor felis, eget semper ante rhoncus fermentum. Donec malesuada, tellus arcu scelerisque odio, in porta ipsum lorem vel sem. Nullam lacus eros, sollicitudin in viverra a, tristique nec dolor. In sit amet dui leo. Etiam vehicula metus egestas metus consequat, eget sollicitudin nisi adipiscing.\
\
Aliquam at erat urna. Maecenas eros lorem, mollis eu eleifend suscipit, commodo vitae ipsum. Nam viverra felis dolor, commodo blandit est ultricies at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in condimentum erat. Aenean sagittis suscipit cursus. Integer eget sem purus. Nullam at vestibulum elit.";

#endif